from django.urls import path
from api.views import (
    ManpowerListAPIView,
    ManpowerRetrieveAPIVIew,
    ManpowerUpdateAPIVIew,
    ManpowerDestroyAPIVIew,
    ManpowerCreateAPIVIew,
    EntryLogListAPIView,
    EntryLogRetrieveAPIVIew,
    EntryLogUpdateAPIVIew,
    EntryLogDestroyAPIVIew,
    EntryLogCreateAPIVIew,
    EmployeesListAPIView,
    EmployeesRetrieveAPIVIew,
    EmployeesUpdateAPIVIew,
    EmployeesDestroyAPIVIew,
    EmployeesCreateAPIVIew,
    SalaryListAPIView,
    SalaryRetrieveAPIVIew,
    SalaryUpdateAPIVIew,
    SalaryDestroyAPIVIew,
    SalaryCreateAPIVIew,
    UserCreateAPIView,
    UserListAPIView,
    UserRetrieveAPIView,
    UserUpdateAPIView,
    UserDestroyAPIView,
    )

app_name = 'employee'   #Declare the app name
urlpatterns = [
   path('manpower/create',ManpowerCreateAPIVIew.as_view() , name = "man_create"),
   path('manpower/',ManpowerListAPIView.as_view() , name = "man_list"),
   path('manpower/<id>',ManpowerRetrieveAPIVIew.as_view() , name = "man_detail"),
   path('manpower/<id>/update',ManpowerUpdateAPIVIew.as_view() , name = "man_update"),
   path('manpower/<id>/delete',ManpowerDestroyAPIVIew.as_view() , name = "man_delete"),
   path('entry/create',EntryLogCreateAPIVIew.as_view() , name = "entry_create"),
   path('user/create',UserCreateAPIView.as_view() , name = "user_create"),
   path('user/',UserListAPIView.as_view() , name = "user_list"),
   path('user/<id>/update',UserUpdateAPIView.as_view() , name = "user_update"),
   path('user/<id>',UserRetrieveAPIView.as_view() , name = "user_retrieve"),
   path('user/<id>/delete',UserDestroyAPIView.as_view() , name = "user_delete"),
   path('entry/',EntryLogListAPIView.as_view() , name = "entry_list"),
   path('entry/<id>',EntryLogRetrieveAPIVIew.as_view() , name = "entry_detail"),
   path('entry/<id>/update',EntryLogUpdateAPIVIew.as_view() , name = "entry_update"),
   path('entry/<id>/delete',EntryLogDestroyAPIVIew.as_view() , name = "entry_delete"),
   path('employee/create',EmployeesCreateAPIVIew.as_view() , name = "employee_create"),
   path('employee/',EmployeesListAPIView.as_view() , name = "employee_list"),
   path('employee/<id>',EmployeesRetrieveAPIVIew.as_view() , name = "employee_detail"),
   path('employee/<id>/update',EmployeesUpdateAPIVIew.as_view() , name = "employee_update"),
   path('employee/<id>/delete',EmployeesDestroyAPIVIew.as_view() , name = "employee_delete"),
   path('salary/create',SalaryCreateAPIVIew.as_view() , name = "salary_create"),
   path('salary/',SalaryListAPIView.as_view() , name = "salary_list"),
   path('salary/<id>',SalaryRetrieveAPIVIew.as_view() , name = "salary_detail"),
   path('salary/<id>/update',SalaryUpdateAPIVIew.as_view() , name = "salary_update"),
   path('salary/<id>/delete',SalaryDestroyAPIVIew.as_view() , name = "salary_delete"),
]
